language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install:
  - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - cnpm install

after_success:
  - sh deploy.sh

branch: master