language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install:
  - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - cnpm install
before_script:
  - chmod 777 deploy.sh
script:
  - deploy.sh

branch: master